Create html heading section
FloriGOIT/parcel-project-GROCERY-team4 pull request #9
Opened 2023-11-01 11:48 UTC by EugenAd

2023-11-01 12:01 UTC, Achilesseb approved these changes

2023-11-01 12:01 UTC, Achilesseb commented on src/index.html
> +      <section class="heading"></section>
not good! Must make a separate file for heading, Include just the file, so all info of the heading will be inside ./partials/heading.html

2023-11-01 19:47 UTC, FloriGOIT commented on src/partials/heading.html
> +<div class="container">
Removed <div class="container">

2023-11-01 20:01 UTC, FloriGOIT requested changes

2023-11-01 20:01 UTC, FloriGOIT commented on src/partials/heading.html
> +<!-- heading-section -->
To be adjusted:
<div class="container"> - remove
<div class="heading-box-title">  - remove
<div class="heading-img"> <picture> - rename images shorter ex. "half orange" -i would prefer to use (if you have time) W descriptor
<div class="heading-watermelon-box"> -  complete tag img
<div class="heading-watermelon-box"> - rename the class ex "fruit-benefits"

2023-11-02 14:15 UTC, FloriGOIT approved these changes

2023-11-02 14:15 UTC, merged